/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.individuals;

import business.enterprise.Enterprise;
import business.individuals.Individual;
import business.useraccount.UserAccount;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.enterprise.AdminWorkAreaJPanel;

/**
 *
 * @author kales
 */
public class FeedbackJPanel extends javax.swing.JPanel {

    JPanel rightJPanel;
    UserAccount userAccount;
    WorkRequest workRequest;
    Individual individual;
    ArrayList<Enterprise> facilityList;

    /**
     * Creates new form FeedbackJPanel
     */
    public FeedbackJPanel(JPanel rightJPanel, UserAccount userAccount, WorkRequest workRequest, Individual individual, ArrayList<Enterprise> facilityList) {
        initComponents();
        populateDropdown();
        this.rightJPanel = rightJPanel;
        this.userAccount = userAccount;
        this.workRequest = workRequest;
        this.individual = individual;
        this.facilityList = facilityList;
    }

    public void populateDropdown() {
        dpdFeedback.removeAllItems();
        dpdFeedback.insertItemAt("--Select--", 0);
        dpdFeedback.insertItemAt("Poor", 1);
        dpdFeedback.insertItemAt("Average", 2);
        dpdFeedback.insertItemAt("Good", 3);
        dpdFeedback.insertItemAt("Very Good", 4);
        dpdFeedback.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        dpdFeedback = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentTxt = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setText("Your Overall Experience:");
        add(jLabel2);
        jLabel2.setBounds(20, 100, 153, 25);

        dpdFeedback.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(dpdFeedback);
        dpdFeedback.setBounds(200, 100, 240, 27);

        jLabel3.setText("Comments:");
        add(jLabel3);
        jLabel3.setBounds(30, 160, 153, 25);

        commentTxt.setColumns(20);
        commentTxt.setRows(5);
        jScrollPane1.setViewportView(commentTxt);

        add(jScrollPane1);
        jScrollPane1.setBounds(200, 170, 230, 84);

        saveBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/save.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn);
        saveBtn.setBounds(220, 309, 160, 60);

        backBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/backbutton.png"))); // NOI18N
        backBtn.setText(" Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(10, 309, 140, 60);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewImages/review.png"))); // NOI18N
        jLabel4.setText(" FEEDBACK");
        add(jLabel4);
        jLabel4.setBounds(40, 20, 220, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (dpdFeedback.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select the rating");
        } else {
            workRequest.setRating(dpdFeedback.getSelectedItem().toString());
            workRequest.setMessage(commentTxt.getText());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        IndividualMyAccountJPanel myAccountJPanel = new IndividualMyAccountJPanel(rightJPanel, userAccount, individual,facilityList);
        rightJPanel.add("MyAccountJPanel", myAccountJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea commentTxt;
    private javax.swing.JComboBox<String> dpdFeedback;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
