/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.individuals;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.individuals.Individual;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sayalipathare
 */
public class IndividualsRegistrationFormJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form IndividualsRegistrationFormJPanel1
     */
    EcoSystem ecoSystem;
    JPanel rightJPanel;
    Individual individual;
    UserAccount userAccount;
    ArrayList<Enterprise> facilityList;
    
    public IndividualsRegistrationFormJPanel1(JPanel rightJPanel, UserAccount userAccount, Individual individual, ArrayList<Enterprise> facilityList) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.individual = individual;
        this.userAccount = userAccount;
        this.facilityList = facilityList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioBtnHealthCare = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioBtnLongTermCareService = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jbtnNext = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();

        jLabel1.setText("**Welcome to IDD Massachusetts Centre**");

        jLabel2.setText("1. Select program you are interested in:");

        jRadioBtnHealthCare.setText("Health Care");

        jLabel4.setText("Program Info: Coverage is through medicaid.");

        jRadioBtnLongTermCareService.setText("Employment care service");
        jRadioBtnLongTermCareService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnLongTermCareServiceActionPerformed(evt);
            }
        });

        jLabel3.setText("Program Info: Helps in living needs and health care");

        jbtnNext.setText("Next >>");
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Note: Employment Care Service is available only for individuals of  18+ age");

        updateBtn.setText("My Account");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioBtnHealthCare)
                                    .addComponent(jRadioBtnLongTermCareService))
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(updateBtn)
                                        .addComponent(jLabel4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnNext)
                            .addComponent(jLabel5))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(updateBtn))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBtnHealthCare)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBtnLongTermCareService)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addComponent(jbtnNext)
                .addGap(71, 71, 71)
                .addComponent(jLabel5)
                .addGap(104, 104, 104))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        // TODO add your handling code here:
        Date date1 = new Date();
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        
        if (!jRadioBtnHealthCare.isSelected() && !jRadioBtnLongTermCareService.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please Select one service to Procees");
            return;
        }
        
        if (jRadioBtnHealthCare.isSelected()) {
            individual.setServiceType("ShortTermService");
        } else {
            individual.setServiceType("LongTermService");
        }
        
        IndividualsRegistrationFormJPanel2 individualsRegJPanel2 = new IndividualsRegistrationFormJPanel2(userAccount, individual, rightJPanel,facilityList);
        rightJPanel.add("individualsRegistrationFormJPanel2", individualsRegJPanel2);
        
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jRadioBtnLongTermCareServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnLongTermCareServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBtnLongTermCareServiceActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        IndividualMyAccountJPanel myAccount = new IndividualMyAccountJPanel(rightJPanel, userAccount, individual,facilityList);
        rightJPanel.add("IndividualMyAccount", myAccount);
        
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioBtnHealthCare;
    private javax.swing.JRadioButton jRadioBtnLongTermCareService;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
