/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.doctor;

import business.employee.Employee;
import business.enterprise.Enterprise;
import business.history.IndividualHistory;
import business.individuals.Individual;
import business.role.Role;
import business.useraccount.UserAccount;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kales
 */
public class IndividualReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IndividualReportJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    WorkRequest workRequest;
    Enterprise enterprise;
    String list[] = {"Mental Issues", "Physical Issues", "Communication Issues"};

    public IndividualReportJPanel(JPanel userProcessContainer, UserAccount userAccount, WorkRequest workRequest, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.workRequest = workRequest;
        this.enterprise = enterprise;
        conditionJList.setListData(list);
        this.firstNameValue.setText(workRequest.getIndividual().getFirstName());
        this.lastNameValue.setText(workRequest.getIndividual().getLastName());
        populateNurses();

    }

    public void populateNurses() {
        DefaultTableModel dtm = (DefaultTableModel) nurseTable.getModel();
        dtm.setRowCount(0);
        Iterator empIterator = enterprise.getEmpMap().entrySet().iterator();
        while (empIterator.hasNext()) {
            Map.Entry mapElement = (Map.Entry) empIterator.next();
            Employee emp = ((Employee) mapElement.getKey());
            UserAccount nurse = ((UserAccount) mapElement.getValue());
            if (nurse.getRoleType().getValue().equals(Role.RoleType.Nurse.getValue())) {
                Object row[] = new Object[1];
                row[0] = emp;
                dtm.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        firstNameValue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastNameValue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conditionJList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentsTxtArea = new javax.swing.JTextArea();
        assignBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        nurseTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setText("First Name:");
        add(jLabel2);
        jLabel2.setBounds(40, 110, 82, 20);

        firstNameValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(firstNameValue);
        firstNameValue.setBounds(140, 110, 124, 26);

        jLabel3.setText("Last Name:");
        add(jLabel3);
        jLabel3.setBounds(290, 110, 80, 20);

        lastNameValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lastNameValue);
        lastNameValue.setBounds(390, 110, 105, 26);

        jLabel4.setText("Condition:");
        add(jLabel4);
        jLabel4.setBounds(40, 160, 74, 20);

        conditionJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(conditionJList);

        add(jScrollPane1);
        jScrollPane1.setBounds(150, 160, 125, 85);

        jLabel5.setText("Comments:");
        add(jLabel5);
        jLabel5.setBounds(30, 270, 82, 20);

        commentsTxtArea.setColumns(20);
        commentsTxtArea.setRows(5);
        jScrollPane2.setViewportView(commentsTxtArea);

        add(jScrollPane2);
        jScrollPane2.setBounds(140, 270, 166, 96);

        assignBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        assignBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/request.png"))); // NOI18N
        assignBtn.setText("Assign To Nurse");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn);
        assignBtn.setBounds(190, 530, 200, 39);

        nurseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nurse Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(nurseTable);

        add(jScrollPane3);
        jScrollPane3.setBounds(30, 400, 437, 113);

        jLabel9.setText("Available Nurse:");
        add(jLabel9);
        jLabel9.setBounds(30, 370, 116, 20);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/user1.png"))); // NOI18N
        jLabel1.setText("INDIVIDUAL INFORMATION");
        add(jLabel1);
        jLabel1.setBounds(50, 10, 410, 60);

        btnBack.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/backbutton.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 530, 100, 39);
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        int[] iarr = conditionJList.getSelectedIndices();
        List<String> selectedIssues = new ArrayList<>();

        int selectedRow = nurseTable.getSelectedRow();
        if (selectedRow >= 0) {
            if (iarr.length == 0 || commentsTxtArea.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter all details to prepare report");
            } else {
                for (int i = 0; i < iarr.length; i++) {
                    selectedIssues.add(String.valueOf(conditionJList.getModel().getElementAt(conditionJList.getSelectedIndex())));
                }
                Individual ind = workRequest.getIndividual();

                for (IndividualHistory id : ind.getHistory()) {
                    id.setComments(commentsTxtArea.getText());
                    id.setCondition(selectedIssues);
                }

                UserAccount nurse = null;
                Employee emp = null;
                Employee e = (Employee) nurseTable.getValueAt(selectedRow, 0);
                Iterator empIterator = enterprise.getEmpMap().entrySet().iterator();

                while (empIterator.hasNext()) {
                    Map.Entry mapElement = (Map.Entry) empIterator.next();
                    Employee e1 = ((Employee) mapElement.getKey());
                    UserAccount ua = ((UserAccount) mapElement.getValue());
                    if (e1.equals(e)) {
                        nurse = ua;
                        emp = e1;
                        break;
                    }
                }
                if (nurse != null) {

                    workRequest.setSender(this.userAccount);
                    workRequest.setStatus("Assigned to Nurse");
                    workRequest.setMessage("");
                    nurse.getWorkQueue().getWorkRequestList().add(workRequest);
                    JOptionPane.showMessageDialog(null, workRequest.getIndividual().getFirstName() + " " + workRequest.getIndividual().getLastName() + " assigned to Nurse " + nurse.getUsername());

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a nurse to assign");
        }
    }//GEN-LAST:event_assignBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextArea commentsTxtArea;
    private javax.swing.JList<String> conditionJList;
    private javax.swing.JLabel firstNameValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lastNameValue;
    private javax.swing.JTable nurseTable;
    // End of variables declaration//GEN-END:variables
}
