/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.systemadmin;

import business.EcoSystem;
import business.network.Network;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dikshadesai
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNetworkJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    public ManageNetworkJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        btnCreateNetwork = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Network"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(160, 30, 322, 95);

        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/backbutton.png"))); // NOI18N
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(147, 240, 120, 42);

        btnCreateNetwork.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCreateNetwork.setText("Create");
        btnCreateNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNetworkActionPerformed(evt);
            }
        });
        add(btnCreateNetwork);
        btnCreateNetwork.setBounds(330, 240, 100, 40);
        add(jLabel1);
        jLabel1.setBounds(240, 30, 0, 0);

        jLabel2.setText("Name");
        add(jLabel2);
        jLabel2.setBounds(170, 150, 36, 16);
        add(nameTextField);
        nameTextField.setBounds(260, 150, 94, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Network.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(30, 20, 50, 60);
    }// </editor-fold>//GEN-END:initComponents

     public void populateTable() {
       DefaultTableModel dtm = (DefaultTableModel) networkJTable.getModel();
        dtm.setRowCount(0);
        for (Network n : system.getNetworkList()) {
            Object row[] = new Object[1];
            row[0] = n;
            dtm.addRow(row);
        }
  
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel = new SystemAdminWorkAreaJPanel(userProcessContainer, system);
        userProcessContainer.add("systemAdminWorkAreaJPanel",systemAdminWorkAreaJPanel);
       
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnCreateNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNetworkActionPerformed
        String name = nameTextField.getText();   
        if(networkNamePatternRegex())
        {
            if(system.checkIfNetworkIsUnique(name))
            {
                Network network=system.createNetwork();
                network.setName(name);
                JOptionPane.showMessageDialog(null, "Network created successfully");
                nameTextField.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Network has already been used. Please enter another network.");
                nameTextField.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter valid network name.");
        }
        
        populateTable();

       
    }//GEN-LAST:event_btnCreateNetworkActionPerformed

    private boolean networkNamePatternRegex() {
        Pattern p = Pattern.compile("^[a-zA-Z-\\s.]+$");
        Matcher m = p.matcher(nameTextField.getText());
        Boolean b = m.matches();
        return b;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnCreateNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTable networkJTable;
    // End of variables declaration//GEN-END:variables
}
