/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.systemadmin;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.role.AdminRole;
import business.role.Role;
import business.role.Role.RoleType;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dikshadesai
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    Enterprise enterprise;
    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        btnCreate.setEnabled(false);
        this.populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterpriseNameTextField = new javax.swing.JTextField();
        dpdEnterpriseType = new javax.swing.JComboBox<>();
        dpdNetwork = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        btnCreateAdmin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 50, 501, 97);

        jLabel1.setText("Network: ");
        add(jLabel1);
        jLabel1.setBounds(260, 200, 61, 16);

        jLabel2.setText("Enterprise Type:");
        add(jLabel2);
        jLabel2.setBounds(260, 251, 101, 16);

        jLabel3.setText("Name:");
        add(jLabel3);
        jLabel3.setBounds(260, 297, 40, 16);
        add(enterpriseNameTextField);
        enterpriseNameTextField.setBounds(392, 292, 141, 26);

        dpdEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(dpdEnterpriseType);
        dpdEnterpriseType.setBounds(386, 247, 147, 27);

        dpdNetwork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dpdNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpdNetworkActionPerformed(evt);
            }
        });
        add(dpdNetwork);
        dpdNetwork.setBounds(386, 196, 147, 27);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(392, 425, 141, 40);

        jLabel4.setText("Username:");
        add(jLabel4);
        jLabel4.setBounds(260, 337, 66, 25);

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        add(usernameTextField);
        usernameTextField.setBounds(392, 336, 141, 26);

        jLabel5.setText("Password:");
        add(jLabel5);
        jLabel5.setBounds(260, 385, 63, 16);
        add(passwordTextField);
        passwordTextField.setBounds(392, 380, 141, 26);

        btnCreateAdmin.setText("Create Admin");
        btnCreateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminActionPerformed(evt);
            }
        });
        add(btnCreateAdmin);
        btnCreateAdmin.setBounds(620, 60, 129, 40);

        btnBack.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/backbutton.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(61, 427, 120, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/Admin3.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(10, 50, 80, 60);
    }// </editor-fold>//GEN-END:initComponents
    
    public void populateTable() {
        dpdNetwork.removeAllItems();
        dpdEnterpriseType.removeAllItems();
        DefaultTableModel model = (DefaultTableModel) enterpriseTable.getModel();
        model.setRowCount(0);
        
        for(Network n: system.getNetworkList()) {
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList())
            {
                Object[] row = new Object[3];
                row[0] = e;
                row[1] = n;
                row[2] = e.getEnterpriseType().getValue();
                model.addRow(row);
            }
        }
    }
    
    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void btnCreateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminActionPerformed
        // TODO add your handling code here:
        dpdNetwork.removeAllItems();
        dpdEnterpriseType.removeAllItems();
        int SelectedRow = enterpriseTable.getSelectedRow();
        if(SelectedRow >= 0) {
            Enterprise e = (Enterprise)enterpriseTable.getValueAt(SelectedRow, 0);
            for(Network n: system.getNetworkList()) {
                for(Enterprise e1: n.getEnterpriseDirectory().getEnterpriseList())
                {
                    if(e1.equals(e)) {
                        enterprise = e;
                        dpdNetwork.insertItemAt(n, 0);
                        dpdNetwork.setSelectedIndex(0);
                        dpdEnterpriseType.insertItemAt(e1.enterpriseType.getValue(), 0);
                        dpdEnterpriseType.setSelectedIndex(0);
                        enterpriseNameTextField.setText(e1.getName());
                        dpdNetwork.setEditable(false);
                        dpdEnterpriseType.setEditable(false);
                        enterpriseNameTextField.setEditable(false);
                        btnCreate.setEnabled(true);
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_btnCreateAdminActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
         if (usernameTextField.getText().equals("") || passwordTextField.getPassword().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out all the details");
        }
        else
            if (usernamePatternCorrect()) {
                if (passwordPatternCorrect()) {
                    String username = usernameTextField.getText();
                    char c[]= passwordTextField.getPassword();
                    String password = String.valueOf(c);
                    System.out.println("list: " + enterprise.getUserAccountDirectory().getUserAccountList());
                    if(enterprise.getUserAccountDirectory().getUserAccountList().isEmpty())
                    {
                        System.out.println("id");
                        enterprise.getUserAccountDirectory().createUserAccount(username, password, new AdminRole(), RoleType.Admin);
                        System.out.println(system.getUserAccountDirectory().getUserAccountList());
                        JOptionPane.showMessageDialog(null, "Admin created successfully");
                    }
                     else
                    {
                        System.out.println("else");
                        JOptionPane.showMessageDialog(null, "Enterprise Admin already exists.");
                    }
                    enterpriseNameTextField.setText("");
                    usernameTextField.setText("");
                    passwordTextField.setText("");
                }
                else {
                    JOptionPane.showMessageDialog(null, "Please enter valid password");
                }
            }
            else 
            {

                JOptionPane.showMessageDialog(null, "Username is invalid. Username must be in the format: xx_xx@xx.xx");
            }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel = new SystemAdminWorkAreaJPanel(userProcessContainer, system);
        userProcessContainer.add("systemAdminWorkAreaJPanel",systemAdminWorkAreaJPanel);
       
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void dpdNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpdNetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpdNetworkActionPerformed

    
        private boolean usernamePatternCorrect() {
        Pattern p = Pattern.compile("^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$");
        Matcher m = p.matcher(usernameTextField.getText());
        Boolean b = m.matches();
        return b;
    }

    private boolean passwordPatternCorrect() {
        Pattern q = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=_])(?=\\S+$).{6,20}$");
        Matcher n = q.matcher(String.valueOf(passwordTextField.getPassword()));
        Boolean c = n.matches();
        return c;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateAdmin;
    private javax.swing.JComboBox<Object> dpdEnterpriseType;
    private javax.swing.JComboBox<Object> dpdNetwork;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
