/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.enterprise;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.Organization.Type;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dikshadesai
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    EcoSystem system;
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.populateTable();
        this.populateDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) organizationTable.getModel();
        model.setRowCount(0);
       
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()) {
                Object[] row = new Object[2];
                row[0] = org;
                model.addRow(row);
        }
    }
    
    public void populateDropdown() {
        dpdOrganizationType.removeAllItems();
        if(enterprise.enterpriseType.getValue().equals("Hospital")) {
            for(Organization.Type type: Organization.Type.values())
            {
                dpdOrganizationType.addItem(type.Doctor);
                dpdOrganizationType.addItem(type.Nurse);
                break;
            }
                
        }
        if(enterprise.enterpriseType.getValue().equals("Facility")) {
            for(Organization.Type type: Organization.Type.values())
            {
                dpdOrganizationType.addItem(type.Reviewer);
                dpdOrganizationType.addItem(type.Caregiver);
                 dpdOrganizationType.addItem(type.Trainer);
                break;
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dpdOrganizationType = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        organizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(180, 70, 382, 100);

        jLabel1.setText("Organization Type:");
        add(jLabel1);
        jLabel1.setBounds(190, 220, 119, 16);

        dpdOrganizationType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(dpdOrganizationType);
        dpdOrganizationType.setBounds(370, 220, 96, 27);

        btnCreate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCreate.setText("Create ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(370, 300, 100, 40);

        btnBack.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/backbutton.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 300, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/organization.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(40, 70, 80, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        Type type = (Type)dpdOrganizationType.getSelectedItem();
        enterprise.getOrganizationDirectory().createOrganization(type);
        JOptionPane.showMessageDialog(null,type + " added successfully");
        this.populateTable();
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
      
       userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
       Component component = componentArray[componentArray.length - 1];
        AdminWorkAreaJPanel dwjp = (AdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<Object> dpdOrganizationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable organizationTable;
    // End of variables declaration//GEN-END:variables
}
